version: "3.9"

services:
  app:
    build:
      context: ./backend
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  frontend:
    build: 
      context: ./frontend
    restart: always
    volumes:
      - frontend-build:/frontend/build
    depends_on:
      - app
      
  nginx:
    build: 
      context: ./nginx
    restart: always
    depends_on:
      - app
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static-data:/vol/static

volumes:
  postgres-data:
  static-data:
  frontend-build:
