# Generated by Django 4.0.4 on 2022-05-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_profile_image_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experiences',
            field=models.ManyToManyField(related_name='UsersExperience', to='core.experience'),
        ),
    ]
