# Generated by Django 4.0.4 on 2022-05-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_experiences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experiences',
            field=models.ManyToManyField(to='core.experience'),
        ),
    ]
