# Generated by Django 4.0.4 on 2023-02-08 13:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_bio_alter_project_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(default='description'),
            preserve_default=False,
        ),
    ]
